### PR TITLE
Add docker and vagrant

### PR DESCRIPTION
**Pull request by Slach**
see old discussion on https://github.com/github/orchestrator-agent/pull/18

### CODE REVIEW

**Comment by Slach** [comment]
@shlomi-noach how i can see https://janky.githubapp.com/9798990/output ?

**Comment by Slach** [comment]
@shlomi-noach 
i try fix cibuild and failed ssl_test

**Comment by shlomi-noach** [comment]
> how i can see https://janky.githubapp.com/9798990/output ?

You cannot. I need to add `travisci` builds for this repo. However, this gets more complicated, since this repo cannot continue being a fork of `outbrain/orchestrator-agent`. And this is because `golang`'s (terrible) coupling of library paths with actual URLs. 

I am likely to destroy this repo and recreate it (under same name).

**Review by shlomi-noach — APPROVED** [review]
Fantastic. Thank you!

**Pull request merged**
