### PR TITLE
Fix precheck(): honour `-b` and target

### PR DESCRIPTION
**Pull request by samveen**
This pull request makes identical fixes to `build.sh` as the `build.sh` for `orchestrator`.

### CODE REVIEW

**Comment by samveen** [comment]
@shlomi-noach A review would be greatly welcome. I got an anniversary alert for this PR :-/ (rebased off master)

**Review by shlomi-noach — APPROVED** [review]
LOL happy anniversary! 
I never saw this PR 😮

**Comment by samveen** [comment]
@shlomi-noach I am unsure why the CI check is stuck. Any ideas?

**Comment by shlomi-noach** [comment]
@samveen yeah that's because this is an internal CI of hours, that cannot be triggered by non-employees. I need to set up TravisCI for this repo.

**Pull request merged**
